//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pEasyPrint
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderAssignment
    {
        public int OrderAssignmentID { get; set; }
        public string OrderNumber { get; set; }
        public Nullable<int> DesignerID { get; set; }
        public Nullable<System.DateTime> AssignDate { get; set; }
        public Nullable<System.DateTime> AcceptRejectDate { get; set; }
        public string RejectReason { get; set; }
        public string AssignedBy { get; set; }
        public Nullable<int> TotalEarnings { get; set; }
        public bool IsDesignStage { get; set; }
        public bool IsProofStage { get; set; }
        public bool IsApproved { get; set; }
        public bool IsPrinting { get; set; }
        public bool IsCompleted { get; set; }
        public string Comments { get; set; }
        public Nullable<int> OrderStage { get; set; }
    }
}
