//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pEasyPrint
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblDesigner
    {
        public int PkDesignerId { get; set; }
        public string DesignerFirstName { get; set; }
        public string DesigenerLastName { get; set; }
        public string Sex { get; set; }
        public Nullable<int> DesignerExperience { get; set; }
        public string DesignerAddress { get; set; }
        public Nullable<int> City { get; set; }
        public Nullable<int> State { get; set; }
        public Nullable<int> Country { get; set; }
        public Nullable<int> Zip { get; set; }
        public string Mobile { get; set; }
        public Nullable<int> Landline { get; set; }
        public string EmailId { get; set; }
        public Nullable<System.DateTime> AddedOn { get; set; }
        public string AddedBy { get; set; }
        public string HoursAvailable { get; set; }
        public string HoursAvailableFrom { get; set; }
        public string HoursAvailableTo { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string Photo { get; set; }
        public string skypeId { get; set; }
        public string CityName { get; set; }
        public string StateName { get; set; }
        public string CountryName { get; set; }
    }
}
