//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pEasyPrint
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblOrder
    {
        public int pkOrderId { get; set; }
        public string OrderNumber { get; set; }
        public string ProjectName { get; set; }
        public string ClientName { get; set; }
        public string ProjectType { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public Nullable<bool> IsStatus { get; set; }
        public Nullable<bool> IsRejected { get; set; }
        public Nullable<bool> IsAccepted { get; set; }
        public string OrderDate { get; set; }
        public Nullable<int> DesignerId { get; set; }
        public Nullable<int> fkContentWritterId { get; set; }
        public Nullable<bool> IsContentAssign { get; set; }
        public Nullable<bool> IsCustomeOrder { get; set; }
        public string BusinessName { get; set; }
    }
}
